name: screentime_buddy
description: "Mission Off-Screen â€“ screen-time missions for kids"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1 # Or the latest version

  # Firebase (stable for your project)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # Local notifications (delay scheduling)
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1 # Added timezone

  # Optional: open Android settings for exact alarms (kept)
  android_intent_plus: ^5.3.1

  # Audio & animation
  audioplayers: ^6.5.0
  lottie: ^3.1.2
  flutter_overlay_window: ^0.5.0
  android_alarm_manager_plus: ^5.0.0
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/milo_fox.png
    - assets/audio/mission_vo_placeholder.mp3
    - assets/audio/celebrate.mp3
    - assets/lottie/celebrate.json